# Generated by Django 3.2.9 on 2022-04-28 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('_id', models.TextField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
                ('original_title', models.TextField()),
                ('original_lang', models.TextField()),
                ('popularity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('vote_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('vote_average', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('overview', models.TextField()),
                ('release_date', models.TextField()),
                ('backdrop_path', models.TextField()),
                ('poster_path', models.TextField()),
                ('youtube_path', models.TextField()),
            ],
        ),
    ]
