# Generated by Django 4.0.4 on 2022-04-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='director',
            field=models.CharField(default='N/A', max_length=20),
            preserve_default=False,
        ),
    ]
