# Generated by Django 3.1 on 2022-05-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('register_date', models.DateField(auto_now=True)),
                ('token', models.CharField(max_length=64)),
            ],
        ),
    ]
