# Generated by Django 3.1 on 2022-05-17 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import movie.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('original_title', models.CharField(blank=True, max_length=120, null=True)),
                ('original_language', models.CharField(blank=True, max_length=2, null=True)),
                ('popularity', models.IntegerField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('vote_average', models.IntegerField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=100, null=True)),
                ('backdrop_path', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube_path', models.CharField(blank=True, max_length=100, null=True)),
                ('genres', djongo.models.fields.ArrayField(model_container=movie.models.Genre)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=200)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
